version: 2

sources:
  - name: desafio_final
    description: Adventure Works tables
    tables:
      - name: product
      - name: productcategories
      - name: productsubcategorie
      - name: unitmeasure
      - name: customer
      - name: store
      - name: specialofferproduct
      - name: specialoffer
      - name: salesreason
      - name: salesorderheadersalesreason
      - name: creditcard
      - name: personcreditcard
      - name: salesterritory
      - name: address
      - name: stateprovince
      - name: countryregion
      - name: salestaxrate
      - name: salesorderheader
      - name: salesorderdetail