version: 2

sources:
  - name: desafio_final
    description: Adventure Works tables
    tables:
      - name: product
      - name: productcategory
      - name: productsubcategory
      - name: customer
      - name: store
      - name: salesperson
      - name: person
      - name: salesreason
      - name: salesorderheadersalesreason
      - name: creditcard
      - name: salesterritory
      - name: address
      - name: stateprovince
      - name: countryregion
      - name: salesorderheader
      - name: salesorderdetail